### ISSUE TITLE
 Getting error while using MTCNN for detecting face

### ISSUE THREAD

**Issue by SusheendharVijay** [timesler/facenet-pytorch#101]
Error:  :   "ValueError: At least one stride in the given numpy array is negative, and tensors with negative strides are not currently supported. (You can probably work around this by making a copy of your array  with array.copy().) "

 Issue in detect_face.py: 
`imgs = torch.as_tensor(imgs, device=device)` 

First time raising an issue sorry for any mistakes, thanks!

**Comment by timesler** [comment]
Thanks for catching this @SusheendharVijay. We should add the `.copy()` in as suggested. You are welcome to make a PR, it will probably be some time before I get to it

**Comment by SusheendharVijay** [comment]
Sure thing, I'll make a PR shortly. Thanks for your reply!
