### ISSUE TITLE
Operations should be defined purely within modules, not within forward pass method

### ISSUE THREAD

**Issue by ctivanovich** [timesler/facenet-pytorch#111]
This is because, if someone (like me) tries to mess around with the model by adding/removing layers and reconstructing the desired portions with `nn.Sequential`, the portions of the forward method that are not contained within the module definitions will not transfer over to the new model, leading to dimensionality errors for the inputs.

For example, 

```
class Block35(nn.Module):

    def __init__(self, scale=1.0):
        super().__init__()

        self.scale = scale

        self.branch0 = BasicConv2d(256, 32, kernel_size=1, stride=1)

        self.branch1 = nn.Sequential(
            BasicConv2d(256, 32, kernel_size=1, stride=1),
            BasicConv2d(32, 32, kernel_size=3, stride=1, padding=1)
        )
        ................................

    def forward(self, x):
        x0 = self.branch0(x)
        x1 = self.branch1(x)
        x2 = self.branch2(x)
        **out = torch.cat((x0, x1, x2), 1)**
        out = self.conv2d(out)
        out = out * self.scale + x
        out = self.relu(out)
        return out
```
In this portion, I believe the `out = torch.cat((x0, x1, x2), 1)` part will not make it into the reassembled model, because it is not itself a module and so will not be counted as a child of the model's architecture, triggering input size errors for the next Block.

**Comment by timesler** [comment]
@ctivanovich it is implemented in the package in the standard way for CNNs in pytorch. Can you give me an example of what you are trying to do. I cannot think of a way to do what you are asking - whether the `torch.cat` is done here or in a sub-module, it will still be executed in the forward pass.

**Comment by ctivanovich** [comment]
@timesler Thank you for responding.

> whether the torch.cat is done here or in a sub-module, it will still be executed in the forward pass.

I guess what I'm trying to figure out is if there is a way to safely reconstruct the forward method, when all you want are certain layers/child modules from the model. I am guessing that it breaks because the forward method is lost, and pytorch constructs a new forward method by simply calling the initiated modules within this method. If the portions of the forward method that are not module calls could be inserted into branch definitions, they would be inserted into a new forward method? But, I guess that's not possible, since when you define a branch, you use nn.Sequential, which expects module objects? I'll play around and see if what I am saying is possible or even makes sense.
