### ISSUE TITLE
Not getting the correct bounding boxes

### ISSUE THREAD

**Issue by Hiteshsaai** [timesler/facenet-pytorch#113]
I am using face-net to detect faces on images, 

mtcnn = MTCNN()
boxes, probs = mtcnn.detect(img)

I used the above code and i got the results as
 [[573.58386  86.23541 621.4201  153.70749]
 [818.31616 213.39238 850.51984 253.68437]]

i am getting the wrong w , h for the bounding boxes. The resultant image looks like this below,
![download](https://user-images.githubusercontent.com/29530488/91339673-0ac3c680-e794-11ea-831c-ec0011b41965.png)

**Comment by timesler** [comment]
@Hiteshsaai the bounding boxes you have provided do not contain w and h. They are `[left, top, right, bottom]`

**Comment by jvdavim** [comment]
> @Hiteshsaai the bounding boxes you have provided do not contain w and h. They are `[left, top, right, bottom]`

Would be great having it in the README.md or some documentation page. I only found it in this issue.
