### ISSUE TITLE
Python Package

### ISSUE THREAD

**Issue by 392781** [timesler/facenet-pytorch#12]
Any chance of making this into a package?

I'd pull request but I'm not sure how hard it is to set that up or if you guys have to do it.

**Comment by timesler** [comment]
@392781 great idea, I'll get it up on PyPI pronto.

**Comment by timesler** [comment]
@392781 should be good to go:
```bash
pip install facenet-pytorch
```
then
```python
import facenet_pytorch
```

Let me know if that all works as expected!

**Comment by 392781** [comment]
> @392781 should be good to go:
> 
> ```shell
> pip install facenet-pytorch
> ```
> 
> then
> 
> ```python
> import facenet_pytorch
> ```
> 
> Let me know if that all works as expected!

Works beautifully.  Thank you!  By the way, thank you for creating this!
