### ISSUE TITLE
@kivancyuksel conversion to the range [0, 1] only occurs in `transforms.ToTensor()` for PIL images. For numpy arrays, the range is not changed. See the following example:

### ISSUE THREAD

**Issue by Darshan-Ramesh** [timesler/facenet-pytorch#121]
@kivancyuksel conversion to the range [0, 1] only occurs in `transforms.ToTensor()` for PIL images. For numpy arrays, the range is not changed. See the following example:
```python
from PIL import Image
import numpy as np
from torchvision import transforms

img = Image.open('data/test_images/bradley_cooper/1.jpg')
trans = transforms.Compose([
    np.float32,
    transforms.ToTensor()
])
img = trans(img)

print(img.min(), img.max())
```
Output:
```bash
tensor(0.) tensor(255.)
```

_Originally posted by @timesler in https://github.com/timesler/facenet-pytorch/issues/89#issuecomment-638502868_

So the images will be in the interval of [-1,1]. Does this have any advantages over having an interval of [0,1]?

**Comment by timesler** [comment]
I doubt there are any advantages to doing it this way, it was simply a method inherited from the davidsandberg/facenet repo.
