### ISSUE TITLE
convert to NCNN 

### ISSUE THREAD

**Issue by quocnhat** [timesler/facenet-pytorch#127]
Thanks for sharing this code, This is not an issue anymore. 
I want to convert this model to ncnn to be able to run on mobile devices. Does anyone give a try?
Any comments are appreciated, thank you

**Comment by bo-bobo** [comment]
> Thanks for sharing this code, This is not an issue anymore. I want to convert this model to ncnn to be able to run on mobile devices. Does anyone give a try? Any comments are appreciated, thank you

 Did you succeed
