### ISSUE TITLE
TypeError: len() of unsized object

### ISSUE THREAD

**Issue by GayatriPurandharT** [timesler/facenet-pytorch#129]
I get this error when I read the image with PIL and even cv2.
`Traceback (most recent call last):
  File "preprocessing_siwm.py", line 81, in <module>
    mtcnn_caller(new_testset_path, image_folder+'/',image)
  File "preprocessing_siwm.py", line 49, in mtcnn_caller
    img_cropped = mtcnn(img, save_path=path+'spoof/'+image+'/'+image+'.png')
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/facenet_pytorch/models/mtcnn.py", line 262, in forward
    batch_boxes, batch_probs, batch_points, img, method=self.selection_method
  File "/usr/local/lib/python3.6/dist-packages/facenet_pytorch/models/mtcnn.py", line 408, in select_boxes
    if len(boxes) == 0:
TypeError: len() of unsized object
`
I tried checking if the image existed using 
`if img is not None:`
But that doesn't help.
Please guide me if I'm missing on something.
Thanks a lot.

**Comment by iam-aditya** [comment]
Use version 1.0.1 it will work.

**Comment by GayatriPurandharT** [comment]
The error occured because the model failed to recognize faces in profile view. I fixed the issue using `mtcnn.detector()` function to extract face points and skip the frame with no detections.

**Comment by SURABHI-GUPTA** [comment]
@iam-aditya which package 1.0.1 version are you taliking about ?

**Comment by iam-aditya** [comment]
https://github.com/timesler/facenet-pytorch/releases/tag/v1.0.1 this one. Or just do _pip install facenet-pytorch==1.0.1_
