### ISSUE TITLE
Precise definition of the parameter min_face_size 

### ISSUE THREAD

**Issue by Saibo-creator** [timesler/facenet-pytorch#153]
Hey,
      The constructor of the class MTCNN has one parameter: min_face_size. According to the doc, 
`min_face_size {int} -- Minimum face size to search for. (default: {20})` this param is used to define the face size, but what is the unit here? pixels?  

My use case is to only keep faces that have high enough resolutions, like 1024*1024 ideally. Should I use` min_face_size = 1024` to achieve that?

Thanks!

**Comment by timesler** [comment]
> Hey,
> The constructor of the class MTCNN has one parameter: min_face_size. According to the doc,
> `min_face_size {int} -- Minimum face size to search for. (default: {20})` this param is used to define the face size, but what is the unit here? pixels?

Yes, pixels in the original image.

> My use case is to only keep faces that have high enough resolutions, like 1024*1024 ideally. Should I use` min_face_size = 1024` to achieve that?

Yep, I think that should work, although that is extremely high resolution for a face. Faces are typically resized to 160x160 before being passed to the face recognition model in this repo.
