### ISSUE TITLE
Further documentation

### ISSUE THREAD

**Issue by iamkucuk** [timesler/facenet-pytorch#16]
Hi. Appriciated for the repo. It's very informative and provides a nice, easy to use pytorch library. However, I find documentations a bit insufficient. Especially if you could explain the test.py, it would be great!

Cheers!

**Comment by timesler** [comment]
Hi @iamkucuk, test.py is a testing file used only for continuous integration (travis-ci), and is not for implementing the models. I will add some documentation to make this clearer, and perhaps change the name of the file.

For an example implementation, see models/utils/example.py instead. Also for additional documentation, you can run `help(MTCNN)` and `help(InceptionResnetV1)` in python after importing the module.
