### ISSUE TITLE
Links to pretrained models not working 

### ISSUE THREAD

**Issue by vlasakjiri** [timesler/facenet-pytorch#165]
Both links to pretrained models mentioned in the readme are not working:
https://drive.google.com/uc?export=download&id=12DYdlLesBl3Kk51EtJsyPS8qA7fErWDX
https://drive.google.com/uc?export=download&id=1TDZVEBudGaEd5POR5X4ZsMvdsh1h68T1

Does anyone have a working link?

**Comment by timesler** [comment]
Thanks for letting me know. The links have now been fixed.
