### ISSUE TITLE
About using multi-GPU 

### ISSUE THREAD

**Issue by SYF111** [timesler/facenet-pytorch#167]
I want to use multi-gpu to train a network while MTCNN is in the network with weights frozen. But when i used nn.DataParallel on the network. It gives me a StopIteration. The code causes the problem is in detect_face.py, line 30 
`model_dtype = next(pnet.parameters()).dtype
`
I' m a rookie , don't know what's wrong. 😢

**Comment by JYeonKim** [comment]
@SYF111 hi, I have a same error.😢

How did you solve the error? I'd appreciate it if you could tell me.

thank you

**Comment by SYF111** [comment]
sorry, I did not figure it out. I just used one single GPU.



---Original---
From: "Juyeon ***@***.***&gt;
Date: Sat, Jan 28, 2023 19:40 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [timesler/facenet-pytorch] About using multi-GPU  (#167)




 
@SYF111 hi, I have a same error.😢
 
How did you solve the error? I'd appreciate it if you could tell me.
 
thank you

**Comment by JYeonKim** [comment]
> sorry, I did not figure it out. I just used one single GPU.
> […](#)
> ---Original--- From: "Juyeon ***@***.***&gt; Date: Sat, Jan 28, 2023 19:40 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [timesler/facenet-pytorch] About using multi-GPU (#167) @SYF111 hi, I have a same error.😢 How did you solve the error? I'd appreciate it if you could tell me. thank you — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

Hi! I found a solution somehow!

`model_dtype = next(pnet.parameters()).dtype`  -> `model_dtype = torch.Tensor([0]).dtype`

then work!
