### ISSUE TITLE
ModuleNotFoundError: No module named 'facenet_pytorch' but I installed it with sudo -H pip3 

### ISSUE THREAD

**Issue by marcoippolito** [timesler/facenet-pytorch#18]
In Ubuntu 18.04.02 Server Edition with Python 3.7.3 and pip 19.0.3 , I installed facenet-pytorch with pip3:

    marco@pc:~/python3venvironments/pytorch-venv/facenet_pytorch$ sudo -H pip3 install facenet-
      pytorch
    Collecting facenet-pytorch
      Using cached https://files.pythonhosted.org/packages/c3/73 
        /7efe44bce34b27e4d2fc32b184478d6a9066a7d111d6499546a30183cb13/facenet_pytorch-
        0.1.0-py3-none-any.whl
    Requirement already satisfied: requests in /usr/local/lib/python3.7/site-packages (from facenet-
      pytorch) (2.22.0)
    Requirement already satisfied: numpy in /usr/local/lib/python3.7/site-packages (from facenet-
      pytorch) (1.17.0)
    Requirement already satisfied: opencv-python in /usr/local/lib/python3.7/site-packages (from 
      facenet-pytorch) (4.1.0.25)
    Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7
      /site-packages (from requests->facenet-pytorch) (1.25.3)
    Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from 
      requests->facenet-pytorch) (2019.6.16)
    Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/site-packages 
      (from requests->facenet-pytorch) (3.0.4)
    Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.7/site-packages (from 
      requests->facenet-pytorch) (2.8)
    Installing collected packages: facenet-pytorch
    Successfully installed facenet-pytorch-0.1.0

In the empty file infer.py I just added this line:

    from facenet_pytorch import MTCNN, InceptionResnetV1

    marco@pc:~/python3venvironments/pytorch-venv/facenet_pytorch$ python3 infer.py 
    Traceback (most recent call last):
      File "infer.py", line 1, in <module>
        from facenet_pytorch import MTCNN, InceptionResnetV1
    ModuleNotFoundError: No module named 'facenet_pytorch'

While trying to install facenet_pytorch with pip (python2) :   

    marco@pc:~/python3venvironments/pytorch-venv/facenet_pytorch$ sudo -H pip install facenet-pytorch
    [sudo] password for marco: 
    DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your  
      Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for  
      Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest
      /development/release-process/#python-2-support
    Collecting facenet-pytorch
      Downloading https://files.pythonhosted.org/packages/ea/6a/ 
        f7b104f7a0493fb9e6801e93102710af011cd9e1a7abb8525503549807b8/facenet-pytorch-
          0.1.0.tar.gz (1.9MB)
         |████████████████████████████████| 1.9MB 8.4MB/s 
        ERROR: Command errored out with exit status 1:
         command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-
           Y4XgoJ/facenet-pytorch/setup.py'"'"'; __file__='"'"'/tmp/pip-install-Y4XgoJ/facenet-pytorch
           /setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', 
          '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-Y4XgoJ/facenet-pytorch/
        Complete output (3 lines):
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
        IOError: [Errno 2] No such file or directory: '/tmp/pip-install-Y4XgoJ/facenet-pytorch/setup.py'
        ----------------------------------------

How to solve the problem?
Looking forward to your kind help.
Marco

**Comment by timesler** [comment]
Hi @marcoippolito, the issue is that you installed the package using `sudo`. You should avoid doing this in general, as it means that python cannot access the installed package later (this is true of any package, not just facenet-pytorch). To use the package, you should install using either
```{bash}
pip3 install facenet-pytorch
```
or
```{bash}
pip3 install --user pacenet-pytorch
```

You will likely also have to uninstall the sudo-installed package first using `sudo -H pip3 uninstall facenet-pytorch`
