### ISSUE TITLE
Issue when using it on Raspberry pi

### ISSUE THREAD

**Issue by Deepdive543443** [timesler/facenet-pytorch#182]
First of all, thanks for the amazing work of this library. It works better than I expect when I tried using it to detect the face in the video stream. But it came with an issue when I tried running it on Raspberry pi. It will throw an Error from detect_face.py when there is a face in the video stream, like:

  File "/home/sonar/archiconda3/envs/TensorTorch/lib/python3.7/site-packages/facenet_pytorch/models/utils/detect_face.py", line 123, in detect_face
    boxes = torch.cat((boxes[ipass, :4], score[ipass].unsqueeze(1)), dim=1)
IndexError: The shape of the mask [4] at index 0 does not match the shape of the indexed tensor [6, 4] at index 0

I'm confused about why it happened. The version of Torch and Torchvision on my pc and RPi should be the same except my pc is using python 3.8 and RPi is 3.7.

**Comment by nighting0le01** [comment]
how did you solve this??

**Comment by Deepdive543443** [comment]
@nighting0le01  Hi there, I was dealing with this issue by using a pre-built PyTorch1.8 wheel from Q-Enigneering. Not sure if this solution is still valid
