### ISSUE TITLE
How to interpret the output's value if the pictures refer to the same person?

### ISSUE THREAD

**Issue by marcoippolito** [timesler/facenet-pytorch#19]
I downloaded from here [https://www.cl.cam.ac.uk/research/dtg/attarchive/facedatabase.html](url) the AT&T database of faces, and I ran facenet-pytorch face detection and recognition pipeline : [https://github.com/timesler/facenet-pytorch/blob/master/examples/infer.ipynb](url) against the first set, s1, of faces refering to the same person:

    Running on device: cpu
    Face detected with probability: 0.999592
    Face detected with probability: 0.999920
    Face detected with probability: 0.996028
    Face detected with probability: 0.995523
    Face detected with probability: 0.999048
    Face detected with probability: 0.999714
    Face detected with probability: 0.999632
    Face detected with probability: 0.999517
    Face detected with probability: 0.999190
    Face detected with probability: 0.986400
              s1        s1        s1        s1        s1        s1        s1        s1        s1        s1
    s1  0.000000  0.782448  0.722293  0.665322  0.737728  0.648552  0.570795  0.704010  0.575219 
    0.840837
    s1  0.782448  0.000000  0.810834  0.763292  0.909566  0.638656  0.799031  0.800380  0.727899 
      1.042302
    s1  0.722293  0.810834  0.000000  0.761772  0.893338  0.750267  0.734262  0.835646  0.819492 
      0.872905
    s1  0.665322  0.763292  0.761772  0.000000  0.705478  0.719182  0.782794  0.754747  0.669086 
      0.812021
    s1  0.737728  0.909566  0.893338  0.705478  0.000000  0.807325  0.617580  0.793141  0.574466 
      0.787223
    s1  0.648552  0.638656  0.750267  0.719182  0.807325  0.000000  0.700938  0.780042  0.625027
      0.894988
    s1  0.570795  0.799031  0.734262  0.782794  0.617580  0.700938  0.000000  0.724698  0.661852 
      0.873944
    s1  0.704010  0.800380  0.835646  0.754747  0.793141  0.780042  0.724698  0.000000  0.644886 
      0.775929
    s1  0.575219  0.727899  0.819492  0.669086  0.574466  0.625027  0.661852  0.644886  0.000000 
      0.773145
    s1  0.840837  1.042302  0.872905  0.812021  0.787223  0.894988  0.873944  0.775929  0.773145 
      0.000000

Why are there such high values, for example between the 2nd and the 5th pictures : 0.909566, or the 2nd and the 10th pictures: 1.042302 ? Shouldn't be all the values rather low being the pictures of the same person? The minimum values are around 0.5, not less: 0.570795, 0.575219, 0.574466
How to interpret then these values?
     
Marco

**Comment by timesler** [comment]
Hi Marco,

Glad to see you got the code working.

The values in the above matrix are the euclidean distances between faces in the feature space. Since the network output is 512-dimensional feature vectors, 1.04 is not a high value. In general, the values you have above indicate the faces are quite similar (which makes sense since they are the same person). For the larger values (like 1.04), it indicates that the faces are less alike, perhaps due to ageing of the person, wearing glasses, hats, etc.
