### ISSUE TITLE
mtcnn returns very dark faces when visualised

### ISSUE THREAD

**Issue by henrypowell87** [timesler/facenet-pytorch#190]
When I run video frames through mtcnn and try to visualize them with plt.imshow they appear extremely dark. I know this is probably a result of how plt.imshow rescales the normalized output of mtcnn but I'm driving myself a bit crazy trying to assure myself that this is nothing to be worried about. Any ideas if this is expected behaviour or should I be getting regularly coloured images out of the network when visualized with imhow?

Cheers,

Henry

**Comment by Divyam10** [comment]
Did you find a solution for this?
