### ISSUE TITLE
output embeddings dimension is weird

### ISSUE THREAD

**Issue by GiilDe** [timesler/facenet-pytorch#199]
my input is torch.Size([1, 3, 160, 160]). Why is the output dimensions torch.Size([1, 1792, 3, 3]) and not 512?

I initialize the model like this - resnet = InceptionResnetV1('vggface2').eval()

**Comment by timesler** [comment]
Can you provide a reproducible example? I haven't observed anything like this behavior.

```python
import torch
from facenet_pytorch import InceptionResnetV1

resnet = InceptionResnetV1('vggface2').eval()

resnet(torch.rand(1, 3, 160, 160)).shape
```

returns:

```
torch.Size([1, 512])
```
