### ISSUE TITLE
how to github folder import

### ISSUE THREAD

**Issue by avernal1819** [timesler/facenet-pytorch#204]
I got the following error while writing the code.

loss = smp.utils.losses.DiceLoss()
AttributeError: module 'segmentation_models_pytorch' has no attribute 'utils'

To solve this, open anaconda prompt and do pip install segmentation_models_pytorch

Even though I did pip install git+https://github.com/qubvel/segmentation_models.pytorch I get an error.

So I downloaded the entire folder and added the segmentation_models_pytorch folder in the project folder, but I don't know what to do to write smp.utils.

**Comment by timesler** [comment]
This error seems to be related to a different python package
