### ISSUE TITLE
resize of non-square bounding boxes

### ISSUE THREAD

**Issue by gschramm** [timesler/facenet-pytorch#205]
When a detected face bounding box is non-square, the resizing in 
https://github.com/timesler/facenet-pytorch/blob/555aa4bec20ca3e7c2ead14e7e39d5bbce203e4b/models/utils/detect_face.py#L312
leads to distortions.
E.g. if the bouding box has width 300:200 (aspect ratio 1.5), and gets resized to 160:160, the face image gets
squeezed in the vertical direction

As a fix, I would suggest to first pad the non-square bounding box to a square size before resizing.

**Comment by timesler** [comment]
This is deliberate as the pretrained model was trained using images prepared this way
