### ISSUE TITLE
Implement MTCNN algorithm fully on GPU

### ISSUE THREAD

**Issue by timesler** [timesler/facenet-pytorch#22]

**Comment by n0obcoder** [comment]
Hi @timesler  ! great repo : D
can u pls tell me how can i train the mtcnn ? i just want to see the code and try to learn from it.
Thanks in advance :)

**Comment by ArtanisCV** [comment]
Is it possible to use torchvision.ops.nms to replace nms on numpy arrays (https://github.com/timesler/facenet-pytorch/blob/master/models/utils/detect_face.py#L166)?
I benchmark this repo and found that numpy-related ops used a lot of cpus and led to low gpu utilization. By removing nms on numpy arrays, MTCNN should be possible to run fully on pytorch (and thus on GPU).

**Comment by timesler** [comment]
> Hi @timesler ! great repo : D
> can u pls tell me how can i train the mtcnn ? i just want to see the code and try to learn from it.
> Thanks in advance :)

Unfortunately, I've never trained MTCNN, so I can't offer much help there, @n0obcoder. I ported pretrained weights from a tensorflow library (which also didn't contain training code). However, there are repos with training scripts which will hopefully be mostly applicable here.

**Comment by timesler** [comment]
> Is it possible to use torchvision.ops.nms to replace nms on numpy arrays (https://github.com/timesler/facenet-pytorch/blob/master/models/utils/detect_face.py#L166)?
> I benchmark this repo and found that numpy-related ops used a lot of cpus and led to low gpu utilization. By removing nms on numpy arrays, MTCNN should be possible to run fully on pytorch (and thus on GPU).

It certainly is possible. I have actually tested torchvision.ops.nms as a replacement, but the performance was worse for some unknown reason. I intend on giving it some real attention soon. I agree that, if done correctly, it should speed up the algorithm.

**Comment by timesler** [comment]
@ArtanisCV Version 2.0.0 of the package has now been released, which used `torchvision.ops.boxes.batched_nms` and uses a more efficient implementation of MTCNN, particularly for batch processing. See #51 for details

**Comment by n0obcoder** [comment]
> > Hi @timesler ! great repo : D
> > can u pls tell me how can i train the mtcnn ? i just want to see the code and try to learn from it.
> > Thanks in advance :)
> 
> Unfortunately, I've never trained MTCNN, so I can't offer much help there, @n0obcoder. I ported pretrained weights from a tensorflow library (which also didn't contain training code). However, there are repos with training scripts which will hopefully be mostly applicable here.

Thanks for the reply ! : )
