### ISSUE TITLE
behavior is incorrect as introduced

### ISSUE THREAD

**Issue by kaleidoscopical** [timesler/facenet-pytorch#28]
https://github.com/timesler/facenet-pytorch/blob/b070a79a1a08304b9c63c8816472ebbaed98d388/models/inception_resnet_v1.py#L259

In this if statements, the dim of last fc layer is modified to the default `num_classes`(=1001). It is incompatible to the description:
```python
# For a model pretrained on VGGFace2
model = InceptionResnetV1(pretrained='vggface2').eval()
```
As a result, the code above will not provide a classifier with `8631` output dim

**Comment by timesler** [comment]
@kaleidoscopical thanks for spotting this! I have pushed a fix to master and have updated the pip package. You can get the bug fix using `pip install --upgrade facenet-pytorch`
