### ISSUE TITLE
MTCNN batching bug

### ISSUE THREAD

**Issue by MDobransky** [timesler/facenet-pytorch#29]
Inputting the batch of 1280x720 images to MTCNN, the PIL format of the images has the width of 1280 and the height of 720, however after converting images to tensors in detect_face function on line 16, the wo is 720 and ho is 1280 which is flipped. 

Then you proceed to concatenate the batch on the shorter side, in my case (batch 16) to [1,3,11520,1280] tensor. Which is in my view an arbitrary decision and it does not really matter which side is height or width. 

However, come to the splitting the detected boxes into the batch on the lines 118-125, you choose the correct axis but incorrect dimension, because you pick the max(wo, ho) where in fact it needs to be a min(wo,ho), as you previously chose to concatenate on the shorter side.

I don't really have the problem with mixing H, W naming as I know that it is hard to be consistent while working with pytorch, cv2 and PIL, but it made it harder to find the bug.

**Comment by timesler** [comment]
Thanks for reporting this @MDobransky, I will investigate and push a fix soon.

**Comment by timesler** [comment]
Fixed by #32
