### ISSUE TITLE
Perform Transfer Learning on Facenet PyTorch

### ISSUE THREAD

**Issue by FrankXinqi** [timesler/facenet-pytorch#30]
Hi. Thank you so much for this excellent work.

I would like to perform transfer learning and finetune to a similar facial expression task where there are only 7 output classes. How can I modify the last layer of Inception VGGFace2? 

Since I do not fully understand the last few layers, I run into some bugs. 
I see the last few layers are FC ->AveragePool -> BN -> Logistic. I do not know which one I should modify. Both replacing the last one or replace starting FC do not work... 

Could you please give me some guidance?

**Comment by timesler** [comment]
If you create a pretrained model instance in the following way, you should have a model that works for 7 output classes:
```python
from facenet_pytorch import InceptionResnetV1

mdl = InceptionResnetV1(pretrained='vggface2', num_classes=7, classify=True)

print(mdl)
```
```
InceptionResnetV1(
  (conv2d_1a): BasicConv2d(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), bias=False)
    (bn): BatchNorm2d(32, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU()
  )
    ...
  (avgpool_1a): AdaptiveAvgPool2d(output_size=1)
  (dropout): Dropout(p=0.6)
  (last_linear): Linear(in_features=1792, out_features=512, bias=False)
  (last_bn): BatchNorm1d(512, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
  (logits): Linear(in_features=512, out_features=7, bias=True)
)
```

Let me know if there are any issues.

**Comment by FrankXinqi** [comment]
Cool! This works!
