### ISSUE TITLE
How to setup this project on windows?

### ISSUE THREAD

**Issue by WaleedPixako** [timesler/facenet-pytorch#31]
Hello, I've cloned this repo, but is there any command to run this project, I've installed the python along with the anaconda, conda, but can't figure out how to run its test examples, if there is any test examples please help me step by step.

Kind Regards

**Comment by timesler** [comment]
Hi @WaleedPixako, have you installed pytorch? If not, install it with one of the following:
* CPU only
```bash
conda install pytorch torchvision cpuonly -c pytorch
```
* GPU
```bash
conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
```
Then try installing this package with pip:
```bash
pip install facenet-pytorch
```

**Comment by ashir-sirius** [comment]
Hi i am using ubuntu server to deploy app. Also i am using miniconda there, so it cannot be able to install using conda. what should be the quick fix. Thanks in advance.

**Comment by Dordor333** [comment]
> Hi i am using ubuntu server to deploy app. Also i am using miniconda there, so it cannot be able to install using conda. what should be the quick fix. Thanks in advance.
> 
> from facenet_pytorch import MTCNN, InceptionResnetV1 ModuleNotFoundError: No module named 'facenet_pytorch'

Did you manage to solve your problem?
