### ISSUE TITLE
Dose MTCNN come with face align

### ISSUE THREAD

**Issue by FrankXinqi** [timesler/facenet-pytorch#34]
Hi does this MTCNN come with face alignment?

**Comment by timesler** [comment]
No, MTCNN does not do face alignment. It does return facial landmarks that are used for alignment, but alignment has not yet been implemented in this repo.

**Comment by kwanUm** [comment]
@timesler does the detected face from MTCNN needs to be aligned before used in the Face Classifier model in order to get an accurate classification? Or does the model deals well well with rotated face images? Thank you

**Comment by matjazmav** [comment]
I have implemented a simple python script, that aligns face using the only eye landmarks. Here is a snippet if anyone needs it.

```py
# ... imports ...

def get_pivot(x, y):
    x1, x2 = sorted(x)
    y1, y2 = sorted(y)
    cx = x1 + (x2 - x1)/2
    cy = y1 + (y2 - y1)/2

    vector_1 = [1, 0]
    vector_2 = [x2 - cx, y2 - cy]

    unit_vector_1 = vector_1 / np.linalg.norm(vector_1)
    unit_vector_2 = vector_2 / np.linalg.norm(vector_2)
    dot_product = np.dot(unit_vector_1, unit_vector_2)
    angle = np.arccos(dot_product)
    return (cx, cy, angle * 180 / np.pi)
    
# ... init mtcnn ...

img_pil = Image.open(img_path).convert("RGB")
_, _, points = mtcnn.detect(img_pil, landmarks=True)

# align
cx, cy, angle = get_pivot(points[0,0:2,0], points[0,0:2,1])
aligned_image = Image.fromarray(
    cv2.cvtColor(
        cv2.warpAffine(
            cv2.cvtColor(np.array(img_pil), cv2.COLOR_RGB2BGR),
            cv2.getRotationMatrix2D((cx, cy),angle,1),
            (img_pil.width, img_pil.height)
        ),
        cv2.COLOR_BGR2RGB
    )
)

# crop
img_cropped = mtcnn(aligned_image)

# embed
img_embedding = resnet(img_cropped.unsqueeze(0))
```

**Comment by AGenchev** [comment]
@matjazmav thanks, any contribution in the desired direction is valuable.
I imagine your snippet gets coordinates of left and right eye to form a line, then calculates the "roll" angle and corrects it.
