### ISSUE TITLE
How can i facenet for real time

### ISSUE THREAD

**Issue by SungbinSon** [timesler/facenet-pytorch#37]
i had face detection for real time
but i can not find the way face recognition
how can i do it?

**Comment by luisjose24** [comment]
Is it possible? or should analyze every part of the streaming video?

**Comment by SungbinSon** [comment]
> Is it possible? or should analyze every part of the streaming video?

just you add the cv2.Videocapture. 
if i can the way of face recognition(face align) i will upload my github

**Comment by timesler** [comment]
Yes it is possible, and there is no need to process an entire video. If you have code that performs face detection in real-time, just pass the output of MTCNN for a frame to an InceptionResnetV1 model.
