### ISSUE TITLE
Use it as a feature extrator

### ISSUE THREAD

**Issue by FrankXinqi** [timesler/facenet-pytorch#38]
Hi Tim,
I would like to use this facenet as a feature extractor, i.e., delete the last few FC layers.
My Code
`model = InceptionResnetV1(pretrained='vggface2', num_classes=8, classify=True).to(device)`
`print(model)`
Result of last few layers:
` (avgpool_1a): AdaptiveAvgPool2d(output_size=1)`
` (dropout): Dropout(p=0.6, inplace=False)`
` (last_linear): Linear(in_features=1792, out_features=512, bias=False)`
`  (last_bn): BatchNorm1d(512, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)`
`  (logits): Linear(in_features=512, out_features=8, bias=True)`
`)'`
Then, I delete the last FC and BN, so I do the following
`model = nn.Sequential(*list(model.children())[:-2])`
`print("After Delete")`
`print(model)`
Result of last few layers:
`  (13): AdaptiveAvgPool2d(output_size=1)`
`  (14): Dropout(p=0.6, inplace=False)`
`  (15): Linear(in_features=1792, out_features=512, bias=False)`

Yes. This architecture is what I want.

But, if I want to use this pretrained weighted to get a 512d output, then I have the following error:
`File "/home/xxx/anaconda3/envs/face_env/lib/python3.7/site/packages/torch/nn/functional.py", line 1371, in linear output = input.matmul(weight.t())`
`RuntimeError: size mismatch, m1: [3584 x 1], m2: [1792 x 512] at /opt/conda/conda-bld/pytorch_1565272271120/work/aten/src/THC/generic/THCTensorMathBlas.cu:273`

**Comment by timesler** [comment]
There is no need to delete or modify any layers to use it as a feature extractor, just set `classify=False`. E.g.,
```
model = InceptionResnetV1(pretrained='vggface2').to(device)
```

Then, when data is passed to the model, it will output 512-dimensional feature vectors.

**Comment by FrankXinqi** [comment]
Thanks. Yes. It works.
However, because I would like to perform another task,  I want a more general feature extractor. It there a way that I can get the output from the last CNN layer (with the pretrained weights).

**Comment by timesler** [comment]
The cleanest way to do this is to write your own pytorch module that inherits from the InceptionResnetV1 class:
```
class FacialFeatureExtractor(InceptionResnetV1):
    def forward(self, x):
        x = self.conv2d_1a(x)
        x = self.conv2d_2a(x)
        x = self.conv2d_2b(x)
        x = self.maxpool_3a(x)
        x = self.conv2d_3b(x)
        x = self.conv2d_4a(x)
        x = self.conv2d_4b(x)
        x = self.repeat_1(x)
        x = self.mixed_6a(x)
        x = self.repeat_2(x)
        x = self.mixed_7a(x)
        x = self.repeat_3(x)
        x = self.block8(x)
        x = self.avgpool_1a(x)
        x = self.dropout(x)
        x = x.view(x.shape[0], -1)
        return x
```

Alternatively, any layers you want to skip you can just set to be equal to `nn.Sequential()`. E.g.,
```
model.logits = nn.Sequential()
```

**Comment by FrankXinqi** [comment]
Thanks. Tim. A great solution.
I have a similar idea, which is to change your InceptionResnetV1.py file directly. Then, I meet another problem. 
However, do I need to change the pretrained weights to match my modified model? For example, since I am planning to use the first 30 layers of the original InceptionNet and cascade some other fancy layers at the end, how can I only load the first 30 layers weights from `vggface2` and make the rest weights randomly initialized?

**Comment by timesler** [comment]
If you change the layers defined in the `__init__` method, then you will not be able to load the vggface2 pretrained weights directly, which is why I suggested modifying only the `forward` method. If you wish to use a subset of layers from InceptionResnetV1, you could save your own state_dict with only the required layers. E.g.,
```python
original_model = InceptionResnetV1(pretrained='vggface2')
state_dict = model.state_dict()

# Print state dict keys
print(state_dict.keys())

# Remove unwanted keys to match desired model
del state_dict['<key to remove>']
# etc

# Save reduced state dict
torch.save(state_dict, '<save path>')
```

Then load the new saved state_dict into your new model. When defining your layers, use something like:
```python
self.resnet = ReducedResnet()
self.resnet.load_state_dict(torch.load('<save path>'))
self.new_layer1 = something
self.new_layer2 = something
etc.
```

Alternatively, the easiest solution is to just use the model defined in my above comment and just ignore the unwanted layers during the forward function:
```python
class NewModel(nn.Module):
    def __init__(self):
        self.resnet = FacialFeatureExtractor(pretrained='vggface2')
        self.new_layer1 = ...

    def forward(self, x):
        x = self.resnet(x)
        x = self.new_layer1(x)
        return(x) 
```
