### ISSUE TITLE
Error downloading pretrained models

### ISSUE THREAD

**Issue by demacdolincoln** [timesler/facenet-pytorch#41]
the code:

```python
resnet = InceptionResnetV1(pretrained='vggface2').eval()
```

the exception:

```~/.conda/envs/pytorch/lib/python3.7/site-packages/facenet_pytorch/models/inception_resnet_v1.py in load_weights(mdl, name)
    333             with open(cached_file, 'wb') as f:
    334                 f.write(r.content)
--> 335         state_dict.update(torch.load(cached_file))
    336 
    337     mdl.load_state_dict(state_dict)

~/.conda/envs/pytorch/lib/python3.7/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    424         if sys.version_info >= (3, 0) and 'encoding' not in pickle_load_args.keys():
    425             pickle_load_args['encoding'] = 'utf-8'
--> 426         return _load(f, map_location, pickle_module, **pickle_load_args)
    427     finally:
    428         if new_fd:

~/.conda/envs/pytorch/lib/python3.7/site-packages/torch/serialization.py in _load(f, map_location, pickle_module, **pickle_load_args)
    601             f.seek(0)
    602 
--> 603     magic_number = pickle_module.load(f, **pickle_load_args)
    604     if magic_number != MAGIC_NUMBER:
    605         raise RuntimeError("Invalid magic number; corrupt file?")

UnpicklingError: invalid load key, '<'.
```

the downloaded file: 

![html](https://user-images.githubusercontent.com/3997886/70080453-53739800-15e5-11ea-9a51-1f8ec6a5e762.png)

*Update: Testing at another time worked normally, I really don't know what google policy for virus scanning on google drive files

**Comment by timesler** [comment]
Hmm, normally the policy is that you can't programatically download files greater than 100MB from Google Drive, which is why the "features" and output weights are downloaded separately and then combined. I have seen the same error occasionally as well. It is usually fixed by just trying again, as you observed.

**Comment by linnabrown** [comment]
Oh, Thanks a lot!!! You save my life!!!!!!!

**Comment by linnabrown** [comment]
> Hmm, normally the policy is that you can't programatically download files greater than 100MB from Google Drive, which is why the "features" and output weights are downloaded separately and then combined. I have seen the same error occasionally as well. It is usually fixed by just trying again, as you observed.

Oh, Thanks a lot!!! You save my life!!!!!!!
