### ISSUE TITLE
The default postprocessing of MTCNN is not in accordance with the original facenet tensorflow repository

### ISSUE THREAD

**Issue by grjhuard** [timesler/facenet-pytorch#42]
From my understanding, the original facenet tensorflow repository was trained by preprocessing the image with a fixed image standardization (more details here :
https://github.com/davidsandberg/facenet/wiki/Training-using-the-VGGFace2-dataset)

Implementation of fixed standardization in the tensorflow repository :
https://github.com/davidsandberg/facenet/blob/096ed770f163957c1e56efa7feeb194773920f6e/src/facenet.py#L120

The issue is that the default postprocessing of MTCNN is prewhitening (https://github.com/timesler/facenet-pytorch/blob/master/models/mtcnn.py#L280), which corresponds to the older preprocessing used in the tensorflow repository.

The default postprocessing should be the fixed image standardization

**Comment by timesler** [comment]
Thanks @grjhuard for spotting this issue. I've now merged the fix into master with some updated tests and example notebooks.
