### ISSUE TITLE
Bug in MTCNN batch prediction

### ISSUE THREAD

**Issue by ArtanisCV** [timesler/facenet-pytorch#47]
If numbox is 0 before any stage (i.e., numbox == 0 in https://github.com/timesler/facenet-pytorch/blob/master/models/utils/detect_face.py#L50), a total_boxes of shape (0, 9) will be appended into batch_boxes.
In contrast, if numbox is non-zero, a total_boxes of shape (x, 5) will be appended (x depends on the following stages).
Thus, when constructing the final results (https://github.com/timesler/facenet-pytorch/blob/master/models/utils/detect_face.py#L135), np.array(batch_boxes) may throw a shape mismatched exception.

**Comment by timesler** [comment]
Thanks for raising this @ArtanisCV. I recently noticed it also. I've pushed a bandaid fix in a PR that fixes it and will update the master branch and the pip package as soon as CI tests pass. Should be in the next hour or so.

When I find time, I will do a bit of a refactor of detect_face.py to make the purpose of total_boxes more self-explanatory and distinct.
