### ISSUE TITLE
Why does the network work best for 160x160 images ?

### ISSUE THREAD

**Issue by akhil451** [timesler/facenet-pytorch#48]
Can you please explain why the network would perform best for 160x160 images because I saw in the readme you had written since it was trained on 160x160 images. But can you give a detailed explanation of why is it so?

**Comment by timesler** [comment]
The InceptionResnetV1 model should work best on images of the same dimension it was trained on. You can use images of a different size and the model will work, it just means that the relationship between face size and the receptive field of features at various levels of the network are different, and this _may_ impact accuracy.
