### ISSUE TITLE
how to setup the pretrained model locally?

### ISSUE THREAD

**Issue by flydragon2018** [timesler/facenet-pytorch#50]
since the internet is too slow to download and frequently disconnected.

I could get the pretained model files some other way.

so how should I set it up locally?

Thank you!

**Comment by timesler** [comment]
The pretrained weights should only need to be downloaded once, the first time you create a pretrained model. After that, they should be stored in the torch cache locally, so nothing needs to be downloaded subsequent times.

However, if the model caching isn't working for you for some reason, the pretrained weights can be downloaded from the links in the table in the repo readme.

**Comment by flydragon2018** [comment]
Thank you for your reply.  
due to internet problem, I can not download it any ONCE !!!!!!!!
however I could get a copied version by email or usb etc.

so what is the local  cached model file setup ?????

**Comment by flydragon2018** [comment]
in other words, which directory should I put these *.pt files in   locally?

**Comment by timesler** [comment]
The location of the pytorch model cache is different for different systems. It's easiest to just load the state dictionaries into the model in the standard pytorch way.

You can loaded the pretrained weights using:
```
from facenet_pytorch import InceptionResnetV1

# For VGGFace2 pretrained weights:
model = InceptionResnetV1(num_classes=8631)
model.load_state_dict(torch.load('<path to .pt file>'))

# For CASIA-webface pretrained weights:
model = InceptionResnetV1(num_classes=10575)
model.load_state_dict(torch.load('<path to .pt file>'))
```

**Comment by timesler** [comment]
If you want to use the pytorch model cache, you will have to download the weights in their split form (they are downloaded in parts).

For VGGFace2, download the following files:
https://drive.google.com/uc?export=download&id=1cWLH_hPns8kSfMz9kKl9PsG5aNV2VSMn
https://drive.google.com/uc?export=download&id=1mAie3nzZeno9UIzFXvmVZrDG3kwML46X
rename them to vggface2_G5aNV2VSMn.pt and vggface2_DG3kwML46X.pt, respectively.

For CASIA-webface, download the following files:
https://drive.google.com/uc?export=download&id=1LSHHee_IQj5W3vjBcRyVaALv4py1XaGy
https://drive.google.com/uc?export=download&id=1QrhPgn1bGlDxAil2uc07ctunCQoDnCzT
rename them to vggface2_Lv4py1XaGy.pt and vggface2_unCQoDnCzT.pt, respectively.

Copy those files into the following directory:
```bash
echo $(python -c "from facenet_pytorch.models.inception_resnet_v1 import get_torch_home; print(get_torch_home())")/checkpoints
```

**Comment by flydragon2018** [comment]
thank you.  the changing names in your reply works up to:
aligned = []
names = []
for x, y in loader:
    x_aligned, prob = mtcnn(x, return_prob=True)
    if x_aligned is not None:
        print('Face detected with probability: {:8f}'.format(prob))
        aligned.append(x_aligned)
        names.append(dataset.idx_to_class[y])

It reports some error:

aligned = torch.stack(aligned).to(device)
embeddings = resnet(aligned).detach().cpu()
aligned = torch.stack(aligned).to(device)
embeddings = resnet(aligned).detach().cpu()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-219b0f1c2234> in <module>()
----> 1 aligned = torch.stack(aligned).to(device)
      2 embeddings = resnet(aligned).detach().cpu()

TypeError: stack(): argument 'tensors' (position 1) must be tuple of Tensors, not Tensor



**Could you please explain the reason why  the pt files were renamed that way?

originally I just put the .pt files in the right  pathto\checkpoints,  however it keeps trying to 
download the files from internet.

Thank you very much.**

**Comment by timesler** [comment]
The files are named that way so that the data can be versioned. The last 10 characters on the file names are taken from the unique hash generated by Google Drive.
