### ISSUE TITLE
Problem with ResNent

### ISSUE THREAD

**Issue by Lourano** [timesler/facenet-pytorch#54]
Hi, When I want to initialise ResNet, I have this problem.

![image](https://user-images.githubusercontent.com/47052805/72902303-e900ed80-3d33-11ea-888b-519fb7e97535.png)

Could You explain what does it mean?

Thanks!

**Comment by nosound2** [comment]
Hi @Lourano , the network tries to download the weights, which are stored separately. Is this path accessible to you?

`https://drive.google.com/uc?export=download&id=1cWLH_hPns8kSfMz9kKl9PsG5aNV2VSMn`

**Comment by Lourano** [comment]
Hi @nosound2, thx you, code already works)
