### ISSUE TITLE
how to upload my own dataset ?

### ISSUE THREAD

**Issue by jordan-bys** [timesler/facenet-pytorch#56]
thanks for this repo , i've a problem , how to upload my own dataset for resnet? does inception resnet with resnet are the same thing ?! 
im new to nn 
thanks for your advice ..

**Comment by timesler** [comment]
Please see the fine-tuning example included in the 'examples' folder of the repo. Inception Resnet is not the same as Resnet, but was inspired by and built upon it. See the original Inception Resnet paper for a description.

**Comment by jordan-bys** [comment]
mtcnn rise this error 

> AttributeError                            Traceback (most recent call last)
<ipython-input-16-a1b6e44286c1> in <module>
      6     frames_tracked = []
      7     print('\rTracking frame: {}'.format(i + 1), end='')
----> 8     boxes,_ = mtcnn.detect(frame)
      9     frame_draw = frame.copy()
     10     draw = ImageDraw.Draw(frame_draw)

c:\users\username\appdata\local\programs\python\python37\lib\site-packages\facenet_pytorch\models\mtcnn.py in detect(self, img, landmarks)
    345                 self.pnet, self.rnet, self.onet,
    346                 self.thresholds, self.factor,
--> 347                 self.device
    348             )
    349 

c:\users\username\appdata\local\programs\python\python37\lib\site-packages\facenet_pytorch\models\utils\detect_face.py in detect_face(imgs, minsize, pnet, rnet, onet, threshold, factor, device)
      9     if not isinstance(imgs, Iterable):
     10         imgs = [imgs]
---> 11     if any(img.size != imgs[0].size for img in imgs):
     12         raise Exception("MTCNN batch processing only compatible with equal-dimension images.")
     13 

c:\users\username\appdata\local\programs\python\python37\lib\site-packages\facenet_pytorch\models\utils\detect_face.py in <genexpr>(.0)
      9     if not isinstance(imgs, Iterable):
     10         imgs = [imgs]
---> 11     if any(img.size != imgs[0].size for img in imgs):
     12         raise Exception("MTCNN batch processing only compatible with equal-dimension images.")
     13 

AttributeError: 'NoneType' object has no attribute 'size'

code 
`import cv2  
capture = cv2.VideoCapture(0)  
while(True):      
    ret, frame = capture.read()     
    frames_tracked = []      
    print('\rTracking frame: {}'.format(i + 1), end='')     
    boxes,_ = mtcnn.detect(frame)     
    frame_draw = frame.copy()     
    draw = ImageDraw.Draw(frame_draw)     
    for box in boxes:
        draw.rectangle(box.tolist(), outline=(255, 0, 0), width=6)          
     frames_tracked.append(frame_draw.resize((640, 360), Image.BILINEAR))      
    d = display.display(frames_tracked[0], display_id=True)     
    i = 1     
    try:        
    while True:
        d.update(frames_tracked[i % len(frames_tracked)]) 
        i += 1     
    except KeyboardInterrupt:
        pass  
    if cv2.waitKey('q') == 27:     
         break  

capture.release() 
cv2.destroyAllWindows()`

**Comment by jordan-bys** [comment]
but whenever i try to detect faces using my webcam 
```
import cv2  
i = 0
capture = cv2.VideoCapture(0)  
while(True):      
    ret, frame = capture.read() 
    frames_tracked = []
    print('\rTracking frame: {}'.format(i + 1), end='')     

    boxes,_ = mtcnn.detect(frame)     
    frame_draw = frame.copy()
    draw = ImageDraw.Draw(frame_draw)     
    for box in boxes:
        draw.rectangle(box.tolist(), outline=(255, 0, 0), width=6)          

        frames_tracked.append(frame_draw.resize((640, 360), Image.BILINEAR))      

d = display.display(frames_tracked[0], display_id=True)     
i = 1     
try:        
    while True:
        d.update(frames_tracked[i % len(frames_tracked)]) 
        i += 1     
except KeyboardInterrupt:
    pass  
if cv2.waitKey('q') == 27:     
     break  

capture.release() 
cv2.destroyAllWindows()

```
it return this error:

> RuntimeError: number of dims don't match in permute
> [this is entire traceback](http://dpaste.com/2NGW9PP)

**Comment by timesler** [comment]
The MTCNN module expects images of PIL.Image class, not cv2 images/numpy arrays. You need to use the following to convert from cv2 to PIL:
```python
import cv2
from PIL import Image
i = 0
capture = cv2.VideoCapture(0)  
while(True):      
    ret, frame = capture.read() 
    frames_tracked = []
    print('\rTracking frame: {}'.format(i + 1), end='')     
    
    frame_pil = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    frame_pil = Image.fromarray(frame_pil)
    boxes,_ = mtcnn.detect(frame_pil)
    
    etc...
```

**Comment by jordan-bys** [comment]
> AttributeError: 'numpy.ndarray' object has no attribute 'load'

i have got this error ! thanks for your help

**Comment by jordan-bys** [comment]
> TypeError: 'NoneType' object is not iterable

`import cv2  
i = 0
capture = cv2.VideoCapture(0)  
while(True):      
    ret, frame = capture.read() 

    frames_tracked = []
    print('\rTracking frame: {}'.format(i + 1), end='')
    frame_pil = cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
    frame_pil = Image.fromarray(frame_pil)
    boxes,_ = mtcnn.detect(frame_pil)
    frame_draw = frame_pil.copy()
    draw = ImageDraw.Draw(frame_draw)     
    for box in boxes:
        draw.rectangle(box.tolist(), outline=(255, 0, 0), width=6)          
        
        frames_tracked.append(frame_draw.resize((640, 360), Image.BILINEAR))      
    d = display.display(frames_tracked[0], display_id=True)     
    i = 1     
    try:        
        while True:
            d.update(frames_tracked[i % len(frames_tracked)]) 
            i += 1     
    except KeyboardInterrupt:
        pass

    if cv2.waitKey('q') == 27:     
         break  

capture.release() 
cv2.destroyAllWindows()`

> TypeError                                 Traceback (most recent call last)
<ipython-input-10-2cadddf48f3d> in <module>
     12     frame_draw = frame_pil.copy()
     13     draw = ImageDraw.Draw(frame_draw)
---> 14     for box in boxes:
     15         draw.rectangle(box.tolist(), outline=(255, 0, 0), width=6)
     16 

>TypeError: 'NoneType' object is not iterable

**Comment by jordan-bys** [comment]
thank you so much 
but how display the video capture from webcam . this only display the first face of first frame 

`    d = display.display(frames_tracked[0], display_id=True)
    i = 1     
    try:        
        while True:
            d.update(frames_tracked[i % len(frames_tracked)]) 
            i += 1     
    except KeyboardInterrupt:
        pass`

**Comment by jordan-bys** [comment]
please let me know , whats going wrong ?

**Comment by dream-in-night** [comment]
> but whenever i try to detect faces using my webcam
> 
> ```
> import cv2  
> i = 0
> capture = cv2.VideoCapture(0)  
> while(True):      
>     ret, frame = capture.read() 
>     frames_tracked = []
>     print('\rTracking frame: {}'.format(i + 1), end='')     
> 
>     boxes,_ = mtcnn.detect(frame)     
>     frame_draw = frame.copy()
>     draw = ImageDraw.Draw(frame_draw)     
>     for box in boxes:
>         draw.rectangle(box.tolist(), outline=(255, 0, 0), width=6)          
> 
>         frames_tracked.append(frame_draw.resize((640, 360), Image.BILINEAR))      
> 
> d = display.display(frames_tracked[0], display_id=True)     
> i = 1     
> try:        
>     while True:
>         d.update(frames_tracked[i % len(frames_tracked)]) 
>         i += 1     
> except KeyboardInterrupt:
>     pass  
> if cv2.waitKey('q') == 27:     
>      break  
> 
> capture.release() 
> cv2.destroyAllWindows()
> ```
> 
> it return this error:
> 
> > RuntimeError: number of dims don't match in permute
> > [this is entire traceback](http://dpaste.com/2NGW9PP)

我把灰度图换成彩色图后没事了，灰度图就会出现这个问题。
