### ISSUE TITLE
Keeping aspect ratio of extracted face image as is when saving

### ISSUE THREAD

**Issue by mohsinkhn** [timesler/facenet-pytorch#59]
We can pass optional argument in `extract_faces` method to keep face image  aspect ratio as is instead of resizing it to square. That way saved images would not have distortion effects of making image square.

I can work on a PR for this, if it makes sense!

**Comment by timesler** [comment]
Hi @mohsinkhn, you can achieve this using the following:
```python
boxes, probs = mtcnn.detect(img)
face = img.crop(boxes[0])
```

However, I will leave this issue open, as it may still be worth implementing in the forward method. If it is, the application of margins around the detected face will have to be handled carefully.
