### ISSUE TITLE
Whats the best margin to init a mtcnn detector?

### ISSUE THREAD

**Issue by neverUseThisName** [timesler/facenet-pytorch#62]
I want to do face crop from images, and then feed to your pretrained model to get 512-d embedding.
Usually models are trained on aligned faces. So my question are:
1. On the training dataset, whats the value of parameter margin to init a mtcnn detector? (MTCNN(margin=?))
2.  When doing inference, is it necessary to align the cropped faces? If so, whats the setting of that alignment?

Thanks for the help.

**Comment by kwanUm** [comment]
Joining the question. Is there any preferred margin to use? What was this model trained on?

**Comment by timesler** [comment]
Sorry for the delayed response, and thank you for raising this - it should be made clear in the documentation.

> 1. On the training dataset, whats the value of parameter margin to init a mtcnn detector? (MTCNN(margin=?))

This will depend on how the InceptionResnetV1 was trained (use the same margin that was used for training). For the pretrained models included in the repo, the best margin is 14 (`margin=14`).

> 2. When doing inference, is it necessary to align the cropped faces? If so, whats the setting of that alignment?

The state-of-the-art performance acheived in the [davidsandberg/facenet repo](https://github.com/davidsandberg/facenet) did not use alignment, so it's potentially not necessary (for VGGFace2 at least). However, if training or infering on other datasets, alignment may or may not help.

**Comment by kwanUm** [comment]
Thanks!
