### ISSUE TITLE
Cannot Import facenet_pytorch

### ISSUE THREAD

**Issue by NourO93** [timesler/facenet-pytorch#63]
I am using Jupyter notebook on Windows. I have python 3.6.4, and I installed facenet_pytorch using 
pip3 install facenet_pytorch
the installation was successful, but I still cannot import it. upon executing
`from facenet_pytorch import MTCNN, InceptionResnetV1`

I still get an error: No module named 'facenet_pytorch' (no other details) 

Can anyone help me with this? Let me know if I need to provide other details.

**Comment by timesler** [comment]
You have presumably installed the package in a different python environment than the one used by Jupyter.

You can try running the following in a cell of your jupyter notebook:
```python
!pip install facenet-pytorch
```
