### ISSUE TITLE
No module named 'facenet_pytorch' but it seems indeed installed

### ISSUE THREAD

**Issue by marcoippolito** [timesler/facenet-pytorch#66]
I'm in this python3 virtualenv:

    (base) marco@pc01:~/PyTorchMatters/facenet_pytorch/examples$ pyenv virtualenvs
      3.7.3/envs/facenet_pytorch (created from /home/marco/.pyenv/versions/venv373)
      3.7.3/envs/venv373 (created from /home/marco/.pyenv/versions/3.7.3)
    * facenet_pytorch (created from /home/marco/.pyenv/versions/venv373)
      venv373 (created from /home/marco/.pyenv/versions/3.7.3)

As far as I understand, the required module is already installed:

    (base) marco@pc01:~/PyTorchMatters/facenet_pytorch/examples$ pip3 install facenet_pytorch
    Requirement already satisfied: facenet_pytorch in /home/marco/.pyenv/versions/3.7.3
    /envs/facenet_pytorch/lib/python3.7/site-packages (2.2.8)
    Requirement already satisfied: requests in /home/marco/.pyenv/versions/3.7.3 
    /envs/facenet_pytorch/lib/python3.7/site-packages (from facenet_pytorch) (2.23.0)
    Requirement already satisfied: numpy in /home/marco/.pyenv/versions/3.7.3
    /envs/facenet_pytorch/lib/python3.7/site-packages (from facenet_pytorch) (1.18.1)
    Requirement already satisfied: chardet<4,>=3.0.2 in /home/marco/.pyenv/versions/3.7.3
    /envs/facenet_pytorch/lib/python3.7/site-packages (from requests->facenet_pytorch) (3.0.4)
    Requirement already satisfied: idna<3,>=2.5 in /home/marco/.pyenv/versions/3.7.3
    /envs/facenet_pytorch/lib/python3.7/site-packages (from requests->facenet_pytorch) (2.9)
    Requirement already satisfied: certifi>=2017.4.17 in /home/marco/.pyenv/versions/3.7.3
    /envs/facenet_pytorch/lib/python3.7/site-packages (from requests->facenet_pytorch) 
    (2019.11.28)
    Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/marco/.pyenv
    /versions/3.7.3/envs/facenet_pytorch/lib/python3.7/site-packages (from 
    requests->facenet_pytorch) (1.25.8)

And with pip freeze it seems indeed installed in its virtualenv:

    (base) marco@pc01:~/PyTorchMatters/facenet_pytorch/examples$ pip3 freeze --local
    certifi==2019.11.28
    chardet==3.0.4
    facenet-pytorch==2.2.8
    idna==2.9
    numpy==1.18.1
    requests==2.23.0
    urllib3==1.25.8

But when I try to execute this one-line-code:

prova.py :

    from facenet_pytorch import MTCNN

I get ModuleNotFoundError: No module named 'facenet_pytorch'

    (base) marco@pc01:~/PyTorchMatters/facenet_pytorch/examples$ python3 prova.py 
    Traceback (most recent call last):
      File "prova.py", line 1, in <module>
        from facenet_pytorch import MTCNN
    ModuleNotFoundError: No module named 'facenet_pytorch'

- pip3 version: pip-20.0.2
- OS: Ubuntu 18.04.4 Desktop
- python version: Python 3.7.4

How to solve the problem?

Marco

**Comment by timesler** [comment]
Do you encounter the same problem when using `pip install facenet-pytorch` and using `python` rather than `python3`?

What do you get when you run `which pip3`, `which pip`, `which python3` and `which python`?

**Comment by marcoippolito** [comment]
Hi Tim!

    (venv373) (base) marco@pc01:~/PyTorchMatters/facenet_pytorch/examples$ which pip3
    /home/marco/.pyenv/shims/pip3

    (venv373) (base) marco@pc01:~/PyTorchMatters/facenet_pytorch/examples$ which 
    pip/home(venv373) (base(venv373) (venv(v(venv373)

    (base) marco@pc01:~/PyTorchMatters/facenet_pytorch/examples$ which python3
    /home/marco/anaconda3/bin/python3

    (venv373) (base) marco@pc01:~/PyTorchMatters/facenet_pytorch/examples$ which python
    /home/marco/anaconda3/bin/python


    (venv373) (base) marco@pc01:~/PyTorchMatters/facenet_pytorch/examples$ pip install facenet-
    pytorch
    Collecting facenet-pytorch
      Using cached https://files.pythonhosted.org/packages/a8/59
    /9e7b0603a8d6a504cc3b1496c0812a575a86336e8d835565f06b41e5c0b2/facenet_pytorch-
    2.2.8-py3-none-any.whl
    Requirement already satisfied: requests in /home/marco/anaconda3/lib/python3.7/site-packages 
    (from facenet-pytorch) (2.22.0)
    Requirement already satisfied: numpy in /home/marco/anaconda3/lib/python3.7/site-packages 
    (from facenet-pytorch) (1.17.2)
    Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/marco
    /anaconda3/lib/python3.7/site-packages (from requests->facenet-pytorch) (1.24.2)
    Requirement already satisfied: certifi>=2017.4.17 in /home/marco/anaconda3/lib/python3.7/site-
    packages (from requests->facenet-pytorch) (2019.9.11)
    Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/marco/anaconda3/lib/python3.7
    /site-packages (from requests->facenet-pytorch) (3.0.4)
    Requirement already satisfied: idna<2.9,>=2.5 in /home/marco/anaconda3/lib/python3.7/site-
    packages (from requests->facenet-pytorch) (2.8)
    Installing collected packages: facenet-pytorch
    Successfully installed facenet-pytorch-2.2.8

What does it mean? I'm bit confused....

**Comment by timesler** [comment]
Does it now just work with `python3` after installing with `pip`? If not, installing with `python3 -m pip install facenet-pytorch` is your safest bet. 

If it works with `python` but not with `python3` it's very likely that they point to different python installations.
