### ISSUE TITLE
face_tracking.py example: NoneType' object has no attribute 'update

### ISSUE THREAD

**Issue by marcoippolito** [timesler/facenet-pytorch#68]
(OpenCV-) (base) marco@pc01:~/PyTorchMatters/facenet_pytorch/examples$ python3    
    face_tracking.py 
    Running on device: cpu
    Tracking frame: 105
    Done
    <PIL.Image.Image image mode=RGB size=640x360 at 0x7F7AD8C86890>
    Traceback (most recent call last):
      File "face_tracking.py", line 89, in <module>
        d.update(frames_tracked[i % len(frames_tracked)])
    AttributeError: 'NoneType' object has no attribute 'update'

But I added the check "is not None":

    # Add to frame list
    if (frames) is not None:
        frames_tracked.append(frame_draw.resize((640, 360), Image.BILINEAR))

    d = display.display(frames_tracked[0], display_id=True)
    i = 1
    try:
        while True:
            if(frames_tracked[i % len(frames_tracked)]) is not None:
                d.update(frames_tracked[i % len(frames_tracked)])
                i += 1
    except KeyboardInterrupt:
        pass

**Comment by imranlivt** [comment]
It seems the object 'd' is of None type here. that is why it could not find the 'update' method. 
You are checking the wrong variable I think. 
The code for checking should be
if d is not None:
    ....your code....

**Comment by marcoippolito** [comment]
@imranlivt Yes, you are right
Thank you very much!!!
