### ISSUE TITLE
invalid argument 0: Sizes of tensors must match except in dimension 0

### ISSUE THREAD

**Issue by jordan-bys** [timesler/facenet-pytorch#71]
when i run `aligned = torch.stack(aligned).to(device=device)
                  embeddings = resnet(aligned).detach().cpu()` 
i get the following error

> RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 1 and 2 in dimension 1 at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensor.cpp:612

**Comment by jordan-bys** [comment]
> when i run `aligned = torch.stack(aligned).to(device=device) embeddings = resnet(aligned).detach().cpu()`
> i get the following error
> 
> > RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 1 and 2 in dimension 1 at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensor.cpp:612

fixed thanks

**Comment by EunseoLEE90** [comment]
how did you fix it?
