### ISSUE TITLE
MTCNN bounding boxes.

### ISSUE THREAD

**Issue by ldulcic** [timesler/facenet-pytorch#8]
Hi @timesler, first of all, tnx a lot for this awesome library :)

Could MTCNN be changed in a way that it also returns bounding boxes of faces detected?
I'll submit a PR for this, check it out if you want this feature in MTCNN.

**Comment by timesler** [comment]
Great idea @ldulcic. I was thinking of doing this, but you beat me to it! It will be particularly important for when we implement a face alignment module as well. I'll run over the [PR](https://github.com/timesler/facenet-pytorch/pull/9) in the next day or two when I get a chance (this repo is just my side hustle).

**Comment by timesler** [comment]
@ldulcic I've made a suggested change in #10 that departs from your original approach a bit. Let me know if it gives you what you need and I will merge with master.
