### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by elferherrera** [timesler/facenet-pytorch#80]
How can I increase the accuracy of the face detection model? When detecting faces in an image Im getting detections where there is no face. I've been playing the thresholds in the detect face and it seems to help a bit but it isnt 100% perfect.

**Comment by timesler** [comment]
You are correct that it is not 100%. You can experiment with the thresholds used by MTCNN (increase them for fewer false positives), or increase the min face size. Both of these are arguments passed when constructing the MTCNN object.

Furthermore, MTCNN is no longer the state-of-the-art in face detection. So if you need better performance, you could look at using a different model, such as RetinaFace.
