### ISSUE TITLE
How to use the net to recognize the different face 

### ISSUE THREAD

**Issue by rocky-DJY** [timesler/facenet-pytorch#82]

**Comment by satinder147** [comment]
Refer to the example notebook. After obtaining the embedding of a face, you can use a clustering algorithm like Kmeans. All the faces which are closer to a particular cluster centre are of the same person.

**Comment by saraEbrahim** [comment]
but where is the mapping between face location and its embedding?

**Comment by satinder147** [comment]
@saraEbrahim First you need to crop the face from the image, there are a number of ways to do this. The simplest one(with least accuracy) is opencv's haar cascades. After you crop out the face you need to resize it to 160x160. Now you can pass the image to the network. 
Like this:
```
img_embedding = resnet(img_cropped.unsqueeze(0))
```
The image embedding's are 512 dimensional. You can use a cluster algorithm like k-means to cluster them into k groups.

**Comment by saraEbrahim** [comment]
Isn't this cropping already done in mtcnn.detect() already? so I just need to crop the output boxes and feed them to resnet(box_img)

**Comment by satinder147** [comment]
@saraEbrahim  I forget to mention that the author provides MTCNN. Yes, you right, you can do that.

**Comment by DJY1995-djy** [comment]
> @saraEbrahim First you need to crop the face from the image, there are a number of ways to do this. The simplest one(with least accuracy) is opencv's haar cascades. After you crop out the face you need to resize it to 160x160. Now you can pass the image to the network.
> Like this:
> 
> ```
> img_embedding = resnet(img_cropped.unsqueeze(0))
> ```
> 
> The image embedding's are 512 dimensional. You can use a cluster algorithm like k-means to cluster them into k groups.
> Have a look at the example notebook for more details.



> @saraEbrahim First you need to crop the face from the image, there are a number of ways to do this. The simplest one(with least accuracy) is opencv's haar cascades. After you crop out the face you need to resize it to 160x160. Now you can pass the image to the network.
> Like this:
> 
> ```
> img_embedding = resnet(img_cropped.unsqueeze(0))
> ```
> 
> The image embedding's are 512 dimensional. You can use a cluster algorithm like k-means to cluster them into k groups.
> Have a look at the example notebook for more details.

so ,the 512 dimensional are feature vectors? and  why not use the fullly connected layers to classify?

**Comment by satinder147** [comment]
@DJY1995-djy  the model acts as a feature extractor. The triplet loss ensures that photos of the same person would lie very close in 512 dimension al space, and that of different faces would lie far. It is a better approach than classifying faces by attaching a fully connected layer. You can use the model as it is, now it is upon you how you want to classify those 512 dimension al embedding. You can use a fully connected layer or a clustering algorithm.
