### ISSUE TITLE
embeddings and face locations with the same order

### ISSUE THREAD

**Issue by saraEbrahim** [timesler/facenet-pytorch#85]
Hi, I can't see in the examples how to get both (face embedding and its location) with the same order in a multiface image?

**Comment by timesler** [comment]
The embeddings will be returned by the `InceptionResnetV1` in the same order they are input. In the following example, the faces and their embeddings are in the same order:

```python
mtcnn = MTCNN(keep_all=True)
resnet = InceptionResnetV1(pretrained='vggface2').eval()

img_fns = glob.glob('data/test_images/*/*.jpg')
imgs = [Image.open(fn).resize((512, 512)) for fn in img_fns]
with torch.no_grad():
    img_faces = mtcnn(imgs)
    embeddings = [resnet(x) for x in img_faces]
```

**Comment by shekarneo** [comment]
Hi can you explain the preprocessing steps to extract embeddings from faces.
