### ISSUE TITLE
Applying "fixed_image_standardization" after "transforms.ToTensor()"

### ISSUE THREAD

**Issue by kivancyuksel** [timesler/facenet-pytorch#89]
I can see that in "examples/finetune.ipynb"   **fixed_image_standardization** is performed after **transforms.ToTensor()**. This is problematic, because **fixed_image_standardization** assumes pixel values in range [0,255], however **transforms.ToTensor()** scales pixel values to be in range [0,1].

```python
def fixed_image_standardization(image_tensor):
    processed_tensor = (image_tensor - 127.5) / 128.0
    return processed_tensor
```
[ToTensor](https://pytorch.org/docs/stable/torchvision/transforms.html#torchvision.transforms.ToTensor)

from examples/finetune.ipynb:
```python
trans = transforms.Compose([
    np.float32,
    transforms.ToTensor(),
    fixed_image_standardization
])
```

**Comment by timesler** [comment]
@kivancyuksel conversion to the range [0, 1] only occurs in `transforms.ToTensor()` for PIL images. For numpy arrays, the range is not changed. See the following example:
```python
from PIL import Image
import numpy as np
from torchvision import transforms

img = Image.open('data/test_images/bradley_cooper/1.jpg')
trans = transforms.Compose([
    np.float32,
    transforms.ToTensor()
])
img = trans(img)

print(img.min(), img.max())
```
Output:
```bash
tensor(0.) tensor(255.)
```

**Comment by kivancyuksel** [comment]
Thank you for the quick response. I don't know how I missed that...

**Comment by Darshan-Ramesh** [comment]
Hi @timesler ,

So, post fixed_image_standardization, the images will be in the interval [-1,1], right? If yes, then the images will appear darker during training?
