### ISSUE TITLE
key names in state_dict conflict

### ISSUE THREAD

**Issue by agsourav** [timesler/facenet-pytorch#92]
mismatching parameter names in the model and the trained vggface2 file

**Comment by timesler** [comment]
@agsourav can you please elaborate? What code did you run to cause this error?

**Comment by agsourav** [comment]
I implemented the inception resnet v1 model as per your repository, however at places the parameter names in model.state_dict() were different from state_dict() loaded from pretrained weights file. The errors were in the part of conv and conv2d naming difference. However, I modified the names of the state_dict keys as per the names in model.state_dict() and it worked absolutely fine.
