### ISSUE TITLE
While making real time face recognition , facing some error ( AttributeError: 'Tensor' object has no attribute 'append')

### ISSUE THREAD

**Issue by deepshikhasharma05** [timesler/facenet-pytorch#97]
Code :
for msg in consumer:
   # aligned = [ ]
   # names = [ ]
    img_np = deserialize(msg.value)
    rgb = cv2.cvtColor(img_np , cv2.COLOR_BGR2RGB)
    x_aligned, prob = mtcnn(rgb, return_prob=True)
    if prob is not None:
        for x,y in loader:
            #print(msg.value)
            #nparr = np.fromstring(msg.value, np.uint8)
            #nparr = np.frombuffer(msg.value, np.uint8)
            #img_np = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
        
            #img_np = cv2.imdecode(np.frombuffer(nparr, dtype=np.uint8), cv2.IMREAD_UNCHANGED)
            logger.info("info")
            # print("----",type(rgb))
            # cv2.imwrite("yolo3.png",rgb)
        
            if x_aligned is not None:
                print('Face detected with probability: {:8f}'.format(prob))
                logger.info('Face detected with probability: {:8f}'.format(prob))  
                aligned.append(x_aligned)
                names.append(dataset.idx_to_class[y])
                aligned = torch.stack(aligned).to(device)
                embeddings = resnet(aligned).detach().cpu()
                dists = [[(e1 - e2).norm().item() for e2 in embeddings] for e1 in embeddings]
                print(pd.DataFrame(dists, columns=names, index=names))

Error : 
Traceback (most recent call last):
  File "consumer.py", line 69, in <module>
    aligned.append(x_aligned)
AttributeError: 'Tensor' object has no attribute 'append'

**Comment by timesler** [comment]
The issue is that you are converting your list, `aligned`, to a torch tensor in the loop, causing it to fail on the second iteration. I'm not able to quite understand your code as it is. It seems you are never using `x` from `for x,y in loader:`. The following code would probably work (I haven't tested it):

```
img_np = deserialize(msg.value)
rgb = cv2.cvtColor(img_np , cv2.COLOR_BGR2RGB)
x_aligned, prob = mtcnn(rgb, return_prob=True)
print('Face detected with probability: {:8f}'.format(prob))
logger.info('Face detected with probability: {:8f}'.format(prob))  
embeddings = resnet(x_aligned).detach().cpu()
```
